import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
// @ts-ignore: Importing global CSS without type declarations
import '@/app/globals.css';
import LenisProvider from './components/LenisProvider';
import NavBar from './components/NavBar';
import ScrollProgressBar from './components/ScrollProgressBar';
import ScrollToTop from './components/ScrollToTop';
import ScrollTriggerReset from './components/ScrollTriggerReset';
import { ViewTransitions } from 'next-view-transitions';
import { TransitionManager } from './components/TransitionManager';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${notoSans.variable} antialiased relative`}>
          <script
            dangerouslySetInnerHTML={{
              __html: `
            history.scrollRestoration = 'manual';
            window.scrollTo(0, 0);
          `,
            }}
          />
          <NavBar />
          <ScrollProgressBar />

          <LenisProvider>
            <ScrollTriggerReset />
            <ScrollToTop />
            <TransitionManager />
            {children}
          </LenisProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
